apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE_NAME-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: eyala/SERVICE_NAME:BUILD_NUMBER
          ports:
            - containerPort: SERVICE_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME-service
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - name: http
      protocol: TCP
      port: SERVICE_PORT
      targetPort: SERVICE_PORT
