apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE_NAME-deployment
  labels:
    app: SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SERVICE_NAME
  template:
    metadata:
      labels:
        app: SERVICE_NAME
    spec:
      containers:
        - name: SERVICE_NAME
          image: eyala/SERVICE_NAME:BUILD_NUMBER
          ports:
            - containerPort: SERVICE_PORT
          env:
            - name: DATABASE_HOST
              value: "10.1.96.24"
            - name: DATABASE_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME-service
spec:
  type: NodePort
  selector:
    app: SERVICE_NAME
  ports:
    - name: http
      protocol: TCP
      port: SERVICE_PORT
      targetPort: SERVICE_PORT
